<?xml version="1.0" encoding="utf-8"?><Database Name="bdVentaLibros" Class="bdVentaLibrosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MARINA-NOTEBOOK\SQLEXPRESS;Initial Catalog=bdVentaLibros;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="bdVentaLibrosConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Autores" Member="Autores">
    <Type Name="Autores">
      <Column Name="idAutor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="apellidos" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nombres" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Autores_Libros" Member="Libros" ThisKey="idAutor" OtherKey="idAutor1" Type="Libros" />
      <Association Name="Autores_Libros1" Member="Libros1" ThisKey="idAutor" OtherKey="idAutor2" Type="Libros" />
      <Association Name="Autores_Libros2" Member="Libros2" ThisKey="idAutor" OtherKey="idAutor3" Type="Libros" />
      <Association Name="Autores_Libros3" Member="Libros3" ThisKey="idAutor" OtherKey="idAutor4" Type="Libros" />
    </Type>
  </Table>
  <Table Name="dbo.Editoriales" Member="Editoriales">
    <Type Name="Editoriales">
      <Column Name="idEditorial" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Association Name="Editoriales_Libros" Member="Libros" ThisKey="idEditorial" OtherKey="idEditorial" Type="Libros" />
    </Type>
  </Table>
  <Table Name="dbo.Estados" Member="Estados">
    <Type Name="Estados">
      <Column Name="idEstado" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Estados_PublicacionIntercambio" Member="PublicacionIntercambio" ThisKey="idEstado" OtherKey="idEstado" Type="PublicacionIntercambio" />
    </Type>
  </Table>
  <Table Name="dbo.Generos" Member="Generos">
    <Type Name="Generos">
      <Column Name="idGenero" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Generos_Libros" Member="Libros" ThisKey="idGenero" OtherKey="idGenero" Type="Libros" />
      <Association Name="Generos_PublicacionIntercambio" Member="PublicacionIntercambio" ThisKey="idGenero" OtherKey="idGenero" Type="PublicacionIntercambio" />
    </Type>
  </Table>
  <Table Name="dbo.Libros" Member="Libros">
    <Type Name="Libros">
      <Column Name="codigoBarra" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="titulo" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="idEditorial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="paginas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="edicion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idGenero" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="foto" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="precio" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="sinopsis" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaAlta" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="idAutor1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idAutor2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idAutor3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idAutor4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Libros_DetallePorPedido" Member="DetallePorPedido" ThisKey="codigoBarra" OtherKey="codigoLibro" Type="DetallePorPedido" />
      <Association Name="Libros_CalificacionPorLibro" Member="CalificacionPorLibro" ThisKey="codigoBarra" OtherKey="codigoLibro" Type="CalificacionPorLibro" />
      <Association Name="Libros_ListaDeseados" Member="ListaDeseados" ThisKey="codigoBarra" OtherKey="codigoLibro" Type="ListaDeseados" />
      <Association Name="Autores_Libros" Member="Autores" ThisKey="idAutor1" OtherKey="idAutor" Type="Autores" IsForeignKey="true" />
      <Association Name="Autores_Libros1" Member="Autores1" ThisKey="idAutor2" OtherKey="idAutor" Type="Autores" IsForeignKey="true" />
      <Association Name="Autores_Libros2" Member="Autores2" ThisKey="idAutor3" OtherKey="idAutor" Type="Autores" IsForeignKey="true" />
      <Association Name="Autores_Libros3" Member="Autores3" ThisKey="idAutor4" OtherKey="idAutor" Type="Autores" IsForeignKey="true" />
      <Association Name="Editoriales_Libros" Member="Editoriales" ThisKey="idEditorial" OtherKey="idEditorial" Type="Editoriales" IsForeignKey="true" />
      <Association Name="Generos_Libros" Member="Generos" ThisKey="idGenero" OtherKey="idGenero" Type="Generos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Localidades" Member="Localidades">
    <Type Name="Localidades">
      <Column Name="idLocalidad" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idProvincia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Localidades_Usuarios" Member="Usuarios" ThisKey="idLocalidad" OtherKey="idLocalidad" Type="Usuarios" />
      <Association Name="Localidades_Pedidos" Member="Pedidos" ThisKey="idLocalidad" OtherKey="idLocalidadEntrega" Type="Pedidos" />
      <Association Name="Provincias_Localidades" Member="Provincias" ThisKey="idProvincia" OtherKey="idProvincia" Type="Provincias" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Perfiles" Member="Perfiles">
    <Type Name="Perfiles">
      <Column Name="idPerfil" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Provincias" Member="Provincias">
    <Type Name="Provincias">
      <Column Name="idProvincia" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Provincias_Localidades" Member="Localidades" ThisKey="idProvincia" OtherKey="idProvincia" Type="Localidades" />
      <Association Name="Provincias_Usuarios" Member="Usuarios" ThisKey="idProvincia" OtherKey="idProvincia" Type="Usuarios" />
      <Association Name="Provincias_Pedidos" Member="Pedidos" ThisKey="idProvincia" OtherKey="idProvinciaEntrega" Type="Pedidos" />
    </Type>
  </Table>
  <Table Name="dbo.UserProfile" Member="UserProfile">
    <Type Name="UserProfile">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(56) NOT NULL" CanBeNull="false" />
      <Association Name="UserProfile_webpages_UsersInRoles" Member="webpages_UsersInRoles" ThisKey="UserId" OtherKey="UserId" Type="webpages_UsersInRoles" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mail" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="contraseña" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="nombreUsuario" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="fechaHoraBaja" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="idProvincia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idLocalidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idPerfil" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fechaHoraAlta" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Usuarios_PublicacionIntercambio" Member="PublicacionIntercambio" ThisKey="idUsuario" OtherKey="idUsuario" Type="PublicacionIntercambio" />
      <Association Name="Usuarios_Pedidos" Member="Pedidos" ThisKey="idUsuario" OtherKey="idUsuario" Type="Pedidos" />
      <Association Name="Usuarios_CalificacionPorLibro" Member="CalificacionPorLibro" ThisKey="idUsuario" OtherKey="idUsuario" Type="CalificacionPorLibro" />
      <Association Name="Usuarios_ListaDeseados" Member="ListaDeseados" ThisKey="idUsuario" OtherKey="idUsuario" Type="ListaDeseados" />
      <Association Name="Localidades_Usuarios" Member="Localidades" ThisKey="idLocalidad" OtherKey="idLocalidad" Type="Localidades" IsForeignKey="true" />
      <Association Name="Provincias_Usuarios" Member="Provincias" ThisKey="idProvincia" OtherKey="idProvincia" Type="Provincias" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.webpages_Membership" Member="webpages_Membership">
    <Type Name="webpages_Membership">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConfirmationToken" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsConfirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastPasswordFailureDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordFailuresSinceLastSuccess" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordChangedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordVerificationToken" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="PasswordVerificationTokenExpirationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.webpages_OAuthMembership" Member="webpages_OAuthMembership">
    <Type Name="webpages_OAuthMembership">
      <Column Name="Provider" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderUserId" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.webpages_Roles" Member="webpages_Roles">
    <Type Name="webpages_Roles">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="webpages_Roles_webpages_UsersInRoles" Member="webpages_UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="webpages_UsersInRoles" />
    </Type>
  </Table>
  <Table Name="dbo.webpages_UsersInRoles" Member="webpages_UsersInRoles">
    <Type Name="webpages_UsersInRoles">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="webpages_Roles_webpages_UsersInRoles" Member="webpages_Roles" ThisKey="RoleId" OtherKey="RoleId" Type="webpages_Roles" IsForeignKey="true" />
      <Association Name="UserProfile_webpages_UsersInRoles" Member="UserProfile" ThisKey="UserId" OtherKey="UserId" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PublicacionIntercambio" Member="PublicacionIntercambio">
    <Type Name="PublicacionIntercambio">
      <Column Name="idPublicacion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="titulo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="foto" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idEstado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idGenero" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="autor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="fechaHoraAlta" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PublicacionIntercambio_Intercambios" Member="Intercambios" ThisKey="idPublicacion" OtherKey="idPublicacionUsuario1" Type="Intercambios" />
      <Association Name="PublicacionIntercambio_Intercambios1" Member="Intercambios1" ThisKey="idPublicacion" OtherKey="idPublicacionUsuario2" Type="Intercambios" />
      <Association Name="Estados_PublicacionIntercambio" Member="Estados" ThisKey="idEstado" OtherKey="idEstado" Type="Estados" IsForeignKey="true" />
      <Association Name="Generos_PublicacionIntercambio" Member="Generos" ThisKey="idGenero" OtherKey="idGenero" Type="Generos" IsForeignKey="true" />
      <Association Name="Usuarios_PublicacionIntercambio" Member="Usuarios" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EstadosIntercambio" Member="EstadosIntercambio">
    <Type Name="EstadosIntercambio">
      <Column Name="idEstado" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="EstadosIntercambio_Intercambios" Member="Intercambios" ThisKey="idEstado" OtherKey="idEstado" Type="Intercambios" />
    </Type>
  </Table>
  <Table Name="dbo.EstadosPedido" Member="EstadosPedido">
    <Type Name="EstadosPedido">
      <Column Name="idEstado" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="EstadosPedido_Pedidos" Member="Pedidos" ThisKey="idEstado" OtherKey="idEstadoPedido" Type="Pedidos" />
    </Type>
  </Table>
  <Table Name="dbo.DetallePorPedido" Member="DetallePorPedido">
    <Type Name="DetallePorPedido">
      <Column Name="idPedido" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="codigoLibro" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="precioUnitario" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Association Name="Libros_DetallePorPedido" Member="Libros" ThisKey="codigoLibro" OtherKey="codigoBarra" Type="Libros" IsForeignKey="true" />
      <Association Name="Pedidos_DetallePorPedido" Member="Pedidos" ThisKey="idPedido" OtherKey="idPedido" Type="Pedidos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pedidos" Member="Pedidos">
    <Type Name="Pedidos">
      <Column Name="idPedido" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fechaHora" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fechaEntrega" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="direccionEntrega" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="idLocalidadEntrega" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idProvinciaEntrega" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idEstadoPedido" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codigoPostalEntrega" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="Pedidos_DetallePorPedido" Member="DetallePorPedido" ThisKey="idPedido" OtherKey="idPedido" Type="DetallePorPedido" />
      <Association Name="Pedidos_Reclamos" Member="Reclamos" ThisKey="idPedido" OtherKey="idPedido" Type="Reclamos" />
      <Association Name="EstadosPedido_Pedidos" Member="EstadosPedido" ThisKey="idEstadoPedido" OtherKey="idEstado" Type="EstadosPedido" IsForeignKey="true" />
      <Association Name="Localidades_Pedidos" Member="Localidades" ThisKey="idLocalidadEntrega" OtherKey="idLocalidad" Type="Localidades" IsForeignKey="true" />
      <Association Name="Provincias_Pedidos" Member="Provincias" ThisKey="idProvinciaEntrega" OtherKey="idProvincia" Type="Provincias" IsForeignKey="true" />
      <Association Name="Usuarios_Pedidos" Member="Usuarios" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CalificacionPorLibro" Member="CalificacionPorLibro">
    <Type Name="CalificacionPorLibro">
      <Column Name="codigoLibro" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="calificacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="comentario" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fechaHora" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Libros_CalificacionPorLibro" Member="Libros" ThisKey="codigoLibro" OtherKey="codigoBarra" Type="Libros" IsForeignKey="true" />
      <Association Name="Usuarios_CalificacionPorLibro" Member="Usuarios" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ListaDeseados" Member="ListaDeseados">
    <Type Name="ListaDeseados">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="codigoLibro" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fechaHora" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Libros_ListaDeseados" Member="Libros" ThisKey="codigoLibro" OtherKey="codigoBarra" Type="Libros" IsForeignKey="true" />
      <Association Name="Usuarios_ListaDeseados" Member="Usuarios" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TipoMensajeUsuario" Member="TipoMensajeUsuario">
    <Type Name="TipoMensajeUsuario">
      <Column Name="idTipoMensaje" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="TipoMensajeUsuario_MensajeUsuario" Member="MensajeUsuario" ThisKey="idTipoMensaje" OtherKey="idTipoMensaje" Type="MensajeUsuario" />
    </Type>
  </Table>
  <Table Name="dbo.MensajeUsuario" Member="MensajeUsuario">
    <Type Name="MensajeUsuario">
      <Column Name="idMensaje" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="mensaje" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="idTipoMensaje" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fechaHora" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TipoMensajeUsuario_MensajeUsuario" Member="TipoMensajeUsuario" ThisKey="idTipoMensaje" OtherKey="idTipoMensaje" Type="TipoMensajeUsuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Intercambios" Member="Intercambios">
    <Type Name="Intercambios">
      <Column Name="idPublicacionUsuario1" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idPublicacionUsuario2" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fechaHora" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="idEstado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="EstadosIntercambio_Intercambios" Member="EstadosIntercambio" ThisKey="idEstado" OtherKey="idEstado" Type="EstadosIntercambio" IsForeignKey="true" />
      <Association Name="PublicacionIntercambio_Intercambios" Member="PublicacionIntercambio" ThisKey="idPublicacionUsuario1" OtherKey="idPublicacion" Type="PublicacionIntercambio" IsForeignKey="true" />
      <Association Name="PublicacionIntercambio_Intercambios1" Member="PublicacionIntercambio1" ThisKey="idPublicacionUsuario2" OtherKey="idPublicacion" Type="PublicacionIntercambio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reclamos" Member="Reclamos">
    <Type Name="Reclamos">
      <Column Name="idReclamo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idPedido" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="mensaje" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Pedidos_Reclamos" Member="Pedidos" ThisKey="idPedido" OtherKey="idPedido" Type="Pedidos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TipoDescuento" Member="TipoDescuento">
    <Type Name="TipoDescuento">
      <Column Name="idTipo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tipo" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="TipoDescuento_Descuentos" Member="Descuentos" ThisKey="idTipo" OtherKey="idTipo" Type="Descuentos" />
    </Type>
  </Table>
  <Table Name="dbo.Descuentos" Member="Descuentos">
    <Type Name="Descuentos">
      <Column Name="idDescuento" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="idTipo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="validez" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaExpiracion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="descuento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TipoDescuento_Descuentos" Member="TipoDescuento" ThisKey="idTipo" OtherKey="idTipo" Type="TipoDescuento" IsForeignKey="true" />
    </Type>
  </Table>
</Database>